/*----- PROTECTED REGION ID(ImageChannelStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        ImageChannelStateMachine.cpp
//
// description : State machine file for the ImageChannel class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <ImageChannel.h>

/*----- PROTECTED REGION END -----*/	//	ImageChannel::ImageChannelStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  The main function of the device is on and ready.
//  OFF      |  The main function of the device is off.
//  MOVING   |  The hardware is moving (in case of a motor for example), or the detector is acquiring.
//  FAULT    |  An error occurred which could not been handled.
//           |  
//           |  This can be a hardware error, a communication error or even a programming error.
//  INIT     |  The device is initializing the communication to the hardware and the hardware itself.
//  ALARM    |  The alarm was caused because of reaching limits, dangerous position or similar circumstances.
//  UNKNOWN  |  The device state cannot be interpreted, so it is unkown.


namespace ImageChannel_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : ImageChannel::is_preselection_allowed()
 *	Description : Execution allowed for preselection attribute
 */
//--------------------------------------------------------
bool ImageChannel::is_preselection_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::preselectionStateAllowed_WRITE) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::preselectionStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::preselectionStateAllowed_READ) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::preselectionStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ImageChannel::is_detectorSize_allowed()
 *	Description : Execution allowed for detectorSize attribute
 */
//--------------------------------------------------------
bool ImageChannel::is_detectorSize_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::detectorSizeStateAllowed_READ) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::detectorSizeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ImageChannel::is_roiOffset_allowed()
 *	Description : Execution allowed for roiOffset attribute
 */
//--------------------------------------------------------
bool ImageChannel::is_roiOffset_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::MOVING ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::roiOffsetStateAllowed_WRITE) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::roiOffsetStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::roiOffsetStateAllowed_READ) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::roiOffsetStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ImageChannel::is_roiSize_allowed()
 *	Description : Execution allowed for roiSize attribute
 */
//--------------------------------------------------------
bool ImageChannel::is_roiSize_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::MOVING ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::roiSizeStateAllowed_WRITE) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::roiSizeStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::roiSizeStateAllowed_READ) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::roiSizeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ImageChannel::is_binning_allowed()
 *	Description : Execution allowed for binning attribute
 */
//--------------------------------------------------------
bool ImageChannel::is_binning_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::OFF ||
			get_state()==Tango::MOVING ||
			get_state()==Tango::FAULT ||
			get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::binningStateAllowed_WRITE) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::binningStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::binningStateAllowed_READ) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::binningStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ImageChannel::is_zeroPoint_allowed()
 *	Description : Execution allowed for zeroPoint attribute
 */
//--------------------------------------------------------
bool ImageChannel::is_zeroPoint_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::zeroPointStateAllowed_READ) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::zeroPointStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : ImageChannel::is_value_allowed()
 *	Description : Execution allowed for value attribute
 */
//--------------------------------------------------------
bool ImageChannel::is_value_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::INIT ||
			get_state()==Tango::UNKNOWN)
		{
		/*----- PROTECTED REGION ID(ImageChannel::valueStateAllowed_READ) ENABLED START -----*/

		/*----- PROTECTED REGION END -----*/	//	ImageChannel::valueStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : ImageChannel::is_GetBlock_allowed()
 *	Description : Execution allowed for GetBlock attribute
 */
//--------------------------------------------------------
bool ImageChannel::is_GetBlock_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::INIT ||
		get_state()==Tango::UNKNOWN)
	{
	/*----- PROTECTED REGION ID(ImageChannel::GetBlockStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	ImageChannel::GetBlockStateAllowed
		return false;
	}
	return true;
}


/*----- PROTECTED REGION ID(ImageChannel::ImageChannelStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	ImageChannel::ImageChannelStateAllowed.AdditionalMethods

}	//	End of namespace
