/*----- PROTECTED REGION ID(TimerChannel.h) ENABLED START -----*/
//=============================================================================
//
// file :        TimerChannel.h
//
// description : Include file for the TimerChannel class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TimerChannel_H
#define TimerChannel_H

#include <tango.h>
#include "../mlzdevice/MLZDevice.h"
#include "../detectorchannel/DetectorChannel.h"


/*----- PROTECTED REGION END -----*/	//	TimerChannel.h

/**
 *  TimerChannel class description:
 *    Base class for channels that control measurement time.
 */

namespace TimerChannel_ns
{
/*----- PROTECTED REGION ID(TimerChannel::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	TimerChannel::Additional Class Declarations

class TimerChannel : public DetectorChannel_ns::DetectorChannel
{

/*----- PROTECTED REGION ID(TimerChannel::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	TimerChannel::Data Members


//	Attribute data members
public:
	Tango::DevDouble	*attr_preselection_read;
	Tango::DevDouble	*attr_value_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TimerChannel(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TimerChannel(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	TimerChannel(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~TimerChannel() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : TimerChannel::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : TimerChannel::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute preselection related methods
 *	Description: Preset time value.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_preselection(Tango::Attribute &attr);
	virtual void write_preselection(Tango::WAttribute &attr);
	virtual bool is_preselection_allowed(Tango::AttReqType type);
/**
 *	Attribute value related methods
 *	Description: Current time value.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_value(Tango::Attribute &attr);
	virtual bool is_value_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : TimerChannel::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:


	//--------------------------------------------------------
	/**
	 *	Method      : TimerChannel::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(TimerChannel::Additional Method prototypes) ENABLED START -----*/
//	Additional Method prototypes

	virtual void read_active(Tango::Attribute &attr);

	virtual void write_active(Tango::WAttribute &attr);

protected:
	virtual bool isMaster(void);


/*----- PROTECTED REGION END -----*/	//	TimerChannel::Additional Method prototypes
};

/*----- PROTECTED REGION ID(TimerChannel::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	TimerChannel::Additional Classes Definitions

}	//	End of namespace

#endif   //	TimerChannel_H
