######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 29 11:15:50 2013
######################################################################

TEMPLATE 	= subdirs

SUBDIRS		+= GraphicsSceneWidget \
		SetupWidget

CONFIG += debug
